version: 2

build:
  os: ubuntu-22.04
  tools:
    python: mambaforge-4.10

conda:
  environment: environment.yml

sphinx:
  builder: html
  # TODO: fix warnings and then set this to true
  fail_on_warning: false